name = "adopt-me"
main = "dist/_worker.js"
workers_dev = true
compatibility_date = "2025-11-10"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "SESSION"
id = "local-session-kv"
preview_id = "local-session-kv"

[env.production]
[[env.production.kv_namespaces]]
binding = "SESSION"
id = "production-session-kv"
