name = "adopt-me"
main = "dist/_worker.js"
workers_dev = true
compatibility_date = "2025-11-10"
compatibility_flags = ["nodejs_compat"]
routes = [
  { pattern = "*example.com/*", zone_name = "example.com" }
]

[[kv_namespaces]]
binding = "SESSION"
id = "local-session-kv"
preview_id = "local-session-kv"

[env.production]
name = "adopt-me-production"
routes = [
  { pattern = "*example.com/*", zone_name = "example.com" }
]

[[env.production.kv_namespaces]]
binding = "SESSION"
id = "production-session-kv"
